<a href="https://colab.research.google.com/github/Certifieddonnie/ML_Test/blob/main/test_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [17]:
import tensorflow as tf
print(tf.version)

# Creating Tensors
tense_1 = tf.Variable("Hello World", tf.string)
tense_2 = tf.Variable(419, tf.int16)
tense_3 = tf.Variable(3.417, tf.float32)

# Rank 0 Tensors
# tf.rank(tense_1)
# tf.rank(tense_2)
# tf.rank(tense_3)

# More Tensors
t4 = tf.Variable([34, 26, 98], tf.int16)
t5 = tf.Variable([["Hello", "World", "hi"], ["me", "Love", "You"]], tf.string)

# Rank 1, 2 Tensors
print(tf.rank(t4))
print(t5.shape)
# tf.rank(t5)


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(1, shape=(), dtype=int32)
(2, 3)


In [50]:
# Changing of shapes

t6 = tf.ones([2, 3, 3], tf.int32)
t7 = tf.reshape(t6, [1, 6, 3])
t8 = tf.reshape(t7, [3, -1])
print(t6)
print(t7)
print(t8)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(1, 6, 3), dtype=int32)
tf.Tensor(
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]], shape=(3, 6), dtype=int32)
