<a href="https://colab.research.google.com/github/Certifieddonnie/ML_Test/blob/main/test_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
!pip install -q sklearn
%tensorflow_version 2.x

  Preparing metadata (setup.py) ... done
Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [54]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc

import tensorflow as tf
# print(tf.version)

# Creating Tensors
tense_1 = tf.Variable("Hello World", tf.string)
tense_2 = tf.Variable(419, tf.int16)
tense_3 = tf.Variable(3.417, tf.float32)

# Rank 0 Tensors
# tf.rank(tense_1)
# tf.rank(tense_2)
# tf.rank(tense_3)

# More Tensors
t4 = tf.Variable([34, 26, 98], tf.int16)
t5 = tf.Variable([["Hello", "World", "hi"], ["me", "Love", "You"]], tf.string)

# Rank 1, 2 Tensors
print(tf.rank(t4))
print(t5.shape)
# tf.rank(t5)


tf.Tensor(1, shape=(), dtype=int32)
(2, 3)


In [50]:
# Changing of shapes

t6 = tf.ones([2, 3, 3], tf.int32)
t7 = tf.reshape(t6, [1, 6, 3])
t8 = tf.reshape(t7, [3, -1])
print(t6)
print(t7)
print(t8)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(1, 6, 3), dtype=int32)
tf.Tensor(
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]], shape=(3, 6), dtype=int32)


In [57]:
# Load dataset.
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv') # training data
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv') # testing data
print(dftrain.head())
y_train = dftrain.pop('survived')
y_eval = dfeval.pop('survived')

   survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y  


In [58]:


# Create a simple dataset with random addition problems and their solutions
def create_dataset(num_samples):
    X = np.random.randint(0, 100, size=(num_samples, 2))
    y = np.sum(X, axis=1)
    return X, y

# Define the neural network architecture
def build_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=(2,)),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1)
    ])
    model.compile(optimizer='adam', loss='mse')
    return model

def main():
    # Create the dataset
    num_samples = 1000
    X_train, y_train = create_dataset(num_samples)

    # Build the model
    model = build_model()

    # Train the model
    model.fit(X_train, y_train, epochs=50, batch_size=32)

    # Test the model with some examples
    X_test = np.array([[10, 20], [30, 40], [50, 60]])
    predictions = model.predict(X_test)
    print("Predictions:", predictions)

if __name__ == "__main__":
    main()


Epoch 1/50
32/32 [==============================] - 1s 2ms/step - loss: 7553.7476
Epoch 2/50
32/32 [==============================] - 0s 2ms/step - loss: 1568.4471
Epoch 3/50
32/32 [==============================] - 0s 2ms/step - loss: 88.3512
Epoch 4/50
32/32 [==============================] - 0s 2ms/step - loss: 43.3576
Epoch 5/50
32/32 [==============================] - 0s 2ms/step - loss: 25.4247
Epoch 6/50
32/32 [==============================] - 0s 2ms/step - loss: 15.0303
Epoch 7/50
32/32 [==============================] - 0s 2ms/step - loss: 8.6464
Epoch 8/50
32/32 [==============================] - 0s 2ms/step - loss: 4.9252
Epoch 9/50
32/32 [==============================] - 0s 2ms/step - loss: 2.9999
Epoch 10/50
32/32 [==============================] - 0s 2ms/step - loss: 1.9312
Epoch 11/50
32/32 [==============================] - 0s 2ms/step - loss: 1.3865
Epoch 12/50
32/32 [==============================] - 0s 2ms/step - loss: 1.1130
Epoch 13/50
32/32 [====================